REFPLTB-2924 : Required meta-dac-sdk kirkstone support for DAC
Reason for change: Faced below build issues for meta-dac-sdk-broadband
1. ERROR: The following layer directories do not exist:
ERROR:    /home/jenkins/jenkinsroot/workspace/sep17/build/../meta-qt5
2. ERROR: ParseError at /home/jenkins/jenkinsroot/workspace/sep17--2/build/../meta-dac-sdk-broadband/recipes-example/example/qt-egl-test.bb:24: Could not inherit file classes/qmake5.bbclass
3. ERROR: No recipes in default available for:
  /home/jenkins/jenkinsroot/workspace/sep17--2/build/../meta-dac-sdk-broadband/recipes-browser/wpewebkit/wpewebkit_%.bbappend
4. ERROR: No recipes in default available for:
  /home/jenkins/jenkinsroot/workspace/sep17--2/build/../meta-dac-sdk-broadband/recipes-browser/wpewebkit/wpewebkit_%.bbappend
Test Procedure: validate the dac build with meta-dac-sdk-broadband repo
Risks: Low

Signed-off-by: ssiras826 <ssiras826@cable.comcast.com>